[package]
name = "shuffle-albums"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpd = "0.0.12"
args = "2.0"
hostname-validator = "1.1.0"
getopts = "0.2"
rand = "0.8"
